### ISSUE TITLE
Ошибка в Rehasher.ps1

### ISSUE THREAD

**Issue by Unearthly86** [Another-1/RT_Pack#25]
Здравствуйте!
Рехэшер выдает ошибку:

InvalidOperation: /home/unearthly86/scripts/rutracker/RT_Pack/_functions.ps1:518
Line | 
 518 |              $bytes = ($bytes).tostring("F0" + "$precision")                                                          
        |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                          
        | You cannot call a method on a null-valued expression.                                                            
Отправлено в рехэш: 16 раздач объёмом  Bytes                                                                            
Осталось: 1425 раздач объёмом 4,0 TB

Решение в Rehasher.ps1 Строка 183
`Write-Log ( "Отправлено в рехэш: $sum_cnt раздач объёмом " + ( $sum_size.size -eq 0 ? 0 : ( to_kmg $sum_size.size 1 ) ) )`
заменить на
`Write-Log ( "Отправлено в рехэш: $sum_cnt раздач объёмом " + ( $sum_size -eq 0 ? 0 : ( to_kmg $sum_size 1 ) ) )`

**Comment by Another-1** [comment]
Ага, спасибо! Поправил.
