### ISSUE TITLE
Adder не обновляет раздачи

### ISSUE THREAD

**Issue by PeachJamCrew** [Another-1/RT_Pack#26]
Система: Ubuntu Server 22.04.4
Скрипты: на авто-обновлении

С четверга 18.07 Аддер перестал обновлять раздачи.
С он так каждую раздачу "обновляет", отчитывается в телеге, но по факту копит не обновленное.
На скринах бота видно как одни и те же раздачи кочуют из отчета в отчет.
Кхм, и сделай, пожалуйста, нормальное логирование. Самому же будет удобней дебажить.
![Screenshot 2024-07-22 200644](https://github.com/user-attachments/assets/689f18f7-d931-4555-8a68-c6511fba386a)
![Screenshot 2024-07-22 201339](https://github.com/user-attachments/assets/474e0e3a-372f-494c-b660-72f26adb0b3c)
![image](https://github.com/user-attachments/assets/0de3f3d4-6fcc-484f-aeaf-1fc69e839358)

**Comment by Another-1** [comment]
Починилось в какой-то момент
